### ISSUE TITLE
Error loading minified angular

### ISSUE THREAD

**Issue by nedp** [neroma/neroma-chat#7]
# Bug Report
## Error loading minified angular
On the branch `maxim/client`, the home page is blank. There is a 404 error on angular.min.js, 
(and lodash.min.js), resulting in a reference error when accessing angular from app.js and templates.js.

It only occurs after running `$ npm install` with the branch checked out. Retaining the npm install from master branch allows the page to load and display, but with broken templates.

It happens independently of browser.

## Steps to reproduce

1. `$ git checkout maxim/clients`
2. `$ rm -rf node_modules`
3. `$ npm install`
4. `$ gulp`
5. Run either `$ node app.js` or `$ nodejs app.js` as appropriate.
6. Open `http://localhost:3000/` in a browser.

## Browsers

This occurs independently of browser.

### Browser console log:

```
"NetworkError: 404 Not Found - http://localhost:3000/js/angular.min.js" 
- angular.min.js

2 * "NetworkError: 404 Not Found - http://localhost:3000/js/lodash.min.js"
- lodash.min.js

ReferenceError: angular is not defined
- var chat = angular.module('chat', []);
  ~~~~~~~~^
- app.js (line 1, col 8)

ReferenceError: angular is not defined
- ...un(["$templateCache", function($templateCache) {$templateCache.put("home.html","...
- templates.js (line 1)

```
## Versions
|       Tool | Version               |
|-----------:|:----------------------|
|       node | v0.12.0               |
|       gulp | 3.9.0                 |
|        npm | 2.1.3                 |
|   Chromium | 43.0.2357.81 (64-bit) |
|    Firefox | 38.0.5                |

**Comment by Druddigon** [comment]
Problem occurs because I was using local files for development. Will be fixed in the updated commit with fixes to Kevin's comments later today.
